// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBPROGRAMLAMA_ODEV.Models;

namespace WEBPROGRAMLAMA_ODEV.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201230004856_Guncelleme1")]
    partial class Guncelleme1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.DiziTur", b =>
                {
                    b.Property<int>("TurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurID");

                    b.ToTable("DiziTurDB");
                });

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.Diziler", b =>
                {
                    b.Property<int>("DiziID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiziAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiziOy")
                        .HasColumnType("int");

                    b.Property<int?>("DiziTurTurID")
                        .HasColumnType("int");

                    b.HasKey("DiziID");

                    b.HasIndex("DiziTurTurID");

                    b.ToTable("DiziDB");
                });

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.Diziler", b =>
                {
                    b.HasOne("WEBPROGRAMLAMA_ODEV.Models.DiziTur", null)
                        .WithMany("DizilerList")
                        .HasForeignKey("DiziTurTurID");
                });

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.DiziTur", b =>
                {
                    b.Navigation("DizilerList");
                });
#pragma warning restore 612, 618
        }
    }
}
