// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBPROGRAMLAMA_ODEV.Models;

namespace WEBPROGRAMLAMA_ODEV.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Sifre")
                        .HasColumnType("Varchar(10)");

                    b.HasKey("AdminID");

                    b.ToTable("AdminTablo");
                });

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.Diziler", b =>
                {
                    b.Property<int>("DiziID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiziAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiziBegeni")
                        .HasColumnType("int");

                    b.Property<string>("DiziBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziDosyaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziIMDB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiziSezonSayi")
                        .HasColumnType("int");

                    b.Property<string>("DiziStudyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziTarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiziTurler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiziID");

                    b.ToTable("DiziTablo");
                });

            modelBuilder.Entity("WEBPROGRAMLAMA_ODEV.Models.Uyeler", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parola")
                        .HasColumnType("int");

                    b.HasKey("UyeID");

                    b.ToTable("UyelerTablo");
                });
#pragma warning restore 612, 618
        }
    }
}
